AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  APIGWMacro:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./macro.yaml
      Parameters: {}

  LoanBroker:
    Type: AWS::Serverless::Application
    # Since the 'LoanBroker' app uses the 'APIGWMacro' the dependency has to be added.
    #
    # Otherwise we run the risk of CFN trying to deploy the 'LoanBroker' stack first. This would result in a failure since the
    # macro is not defined at this point.
    DependsOn:
      - APIGWMacro
    Properties:
      Location: ./app.yaml
      Parameters: {}

Outputs:
  APIGWMacroFunctionLogs:
    Value: !Sub ${APIGWMacro.Outputs.APIGWMacroFunctionLogs}

  BrokerAPIEntryMethod:
    Value: !Sub ${LoanBroker.Outputs.BrokerAPIEntryMethod}
  BrokerStateMachineArn:
    Value: !Sub ${LoanBroker.Outputs.BrokerStateMachineArn}
